Automate the GSMA documentation creation of RM
anuket-project/RM pull request #33
Opened 2024-09-06 04:13 UTC by Aryan-Singla

Automate the GSMA documentation creation of RM

2024-09-10 10:38 UTC, walterkozlowski approved these changes

2024-09-11 07:45 UTC, CsatariGergely requested changes

2024-09-11 07:45 UTC, CsatariGergely commented on doc/ref_model/tox.ini
> +  doc8 . --ignore-path .tox --ignore-path build --ignore-path gsma --ignore D001
```suggestion
  doc8 . --ignore-path .tox --ignore-path build --ignore-path gsma --ignore D001 --ignore D002
```

2024-09-17 14:22 UTC, CsatariGergely approved these changes

2024-09-17 14:22 UTC, CsatariGergely commented
@walterkozlowski this is ready for merger
Thanks @Aryan-Singla for the great work

2024-09-22 12:37 UTC, CsatariGergely approved these changes

2024-09-25 09:35 UTC, merged