[RM Ch2] To pass Action fail
anuket-project/RM pull request #44
Opened 2024-11-20 11:34 UTC by petorre

To pass action fail https://github.com/anuket-project/RM/actions/runs/11930908117/job/33252646132 . If this table fix works, I'll check where else it fails. If this table fix doesn't work, I'll then rework all tables to new format.

2024-11-28 15:18 UTC, CsatariGergely requested changes

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Management
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Management
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Management
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Control
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Data-centre Storage
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Data-centre Storage
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Edge Cloud
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Edge Cloud
```

2024-11-28 15:18 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.rst
> +   * -
```suggestion
   * - Split Control/User Plane Edge Cloud
```

2024-11-28 23:01 UTC, petorre commented
Not it seems to builds .docx well.

2024-12-04 09:53 UTC, walterkozlowski approved these changes
Approved after reviewing in the RM call.

2024-12-09 20:05 UTC, CsatariGergely approved these changes

2024-12-10 09:00 UTC, merged